apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hzvvb0a5g-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hzvvb0a5g-nodejs 
  name: hzvvb0a5g-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hzvvb0a5g-nodejs 
